#!/usr/bin/env node
'use strict';

const program = require('commander');

let listFunction = (directory, options) => {
	//if (options.all)	
}

program
	.version('0.0.1')
	.command('list [directory]') // optional
	.description('List files and folders')
	.option('-a, --all','List all files and folders')
	.option('-l, --long','')
	.action(listFunction);

program.parse(process.argv);
