#!/usr/bin/env node

const program  = require('commander');
const chalk = require('chalk');

program
	.version('0.0.3', '-v, --version')
	.command('add', 'add todo item').alias('a')
	.command('ls', 'list todo items').alias('l')
	.command('lsf', 'list finished todo items').alias('lf')
	.command('co', 'change order of two items').alias('c')
	.command('fin', 'finish todo item').alias('f')
	.command('rm', 'remove todo item').alias('r') 
	.command('keygen', 'generate key from https://tdls.dev').alias('kg')
	.command('setuserinfo', 'set user info from https://tdls.dev').alias('sui')
	.command('mkch', 'make channel').alias('mc') // [TODO] 여기서부턴 아직 미구현
	.command('lsch', 'list subscribed channels').alias('lc') // TODO : ls 에 합치기
	.command('subch', 'subscribe channel').alias('sc')
	.command('unsubch', 'unsubscribe channel').alias('usc')
	.command('pubch', 'publish todo item').alias('pc')

/*
program
	.command('*', { noHelp: true })
	.action(() => {
		console.error(chalk.red.bold('Wrong command'));
		program.help();
	});
*/

program
	.parse(process.argv);

if (program.args.length === 0) program.help();

