#!/usr/bin/env node

const program  = require('commander');
const chalk = require('chalk');

program
	.version('0.0.2')
	.command('add', 'add todo item').alias('a')
	.command('ls', 'list todo items').alias('l')
	.command('lsf', 'list finished todo items').alias('lf')
	.command('co', 'change order of two items').alias('c')
	.command('fin', 'finish todo item').alias('f')
	.command('rm', 'remove todo item').alias('r')
	.command('mkch', 'make channel').alias('mc')
	.command('lsch', 'list subscribed channels').alias('lc') // TODO : ls 에 합치기
	.command('rmch', 'remove subscribed channel').alias('rc')
	.command('subch', 'subscribe channel').alias('sc')
	.command('pubch', 'publish todo item').alias('pc')
	.parse(process.argv)

if (program.args.length === 0) program.help();

