#!/usr/bin/env node

const program  = require('commander');
const chalk = require('chalk');

program
	.version('0.1.0', '-v, --version')
	.command('add', 'add todo item').alias('a')
	.command('ls', 'list todo items').alias('l')
	.command('lsf', 'list finished todo items').alias('lf')
	.command('cpr', 'change the priority of an item').alias('cp')
	.command('fin', 'finish todo item').alias('f')
	.command('rm', 'remove todo item').alias('r') 
	.command('push', 'push local todo items to remote server https://tdls.dev').alias('p') 
	.command('keygen', 'generate key through https://tdls.dev').alias('kg')
	.command('setinfo', 'set user info through https://tdls.dev').alias('si')
	.command('log', 'write tech-blog article to https://tdls.dev using markdown file').alias('lg')
	.command('mkch', 'make channel').alias('mc') // [TODO] 여기서부턴 아직 미구현
	.command('lsch', 'list subscribed channels').alias('lc') // TODO : ls 에 합치기
	.command('subch', 'subscribe channel').alias('sc')
	.command('unsubch', 'unsubscribe channel').alias('usc')
	.command('pubch', 'publish todo item').alias('pc')

/*
program
	.command('*', { noHelp: true })
	.action(() => {
		console.error(chalk.red.bold('Wrong command'));
		program.help();
	});
*/

program
	.parse(process.argv);

if (program.args.length === 0) program.help();

