#!/usr/bin/env node

const program  = require('commander');
const chalk = require('chalk');

const fs = require('fs');

program
	.option('-t, --todo <required>', 'Todo') 
	.option('-s, --secret', 'Secret mode')
	.parse(process.argv);

/**
 *	Options
 */
const todo = program.todo;
const secret = program.secret ? program.secret : false;


/**
 *	Validation	
 */
if (!todo && !secret) {
	console.error(chalk.red.bold('Options required'));
	if (!todo) program.help();
	process.exit(1);
}

/**
 *	Verbose	
 */
console.log(chalk.green.bold('Add command ; '), "+", chalk.white.underline(todo));
if (secret)
	console.log(chalk.red.bold('- Secret mode -'));
else
	console.log(chalk.cyan.bold('- Public mode -'));
	

/**
 *	Read JSON file	
 */
let todos = []
fs.readFile('todos.json', 'utf-8', (err, data) => {
	if (err) {
		console.error(chalk.red.bold(err));
		console.log(chalk.yellow.bold("--> New file will be created"));
	} else {
		todos = JSON.parse(data);
	}

	// add item
	const item = {'todo': todo, 'secret': secret};
	todos.push(item);
	
	/**
	 *	Write JSON file
	 */
	fs.writeFile('todos.json', JSON.stringify(todos), 'utf-8', (err) => {
		if (err) {
			console.error(chalk.red.bold(err));	
		} else {
			console.log(chalk.green.bold('Added Successfully'));	
		}
	});
	// fin write
});

