#!/usr/bin/env node

const program  = require('commander');
const chalk = require('chalk');

const fs = require('fs');

const globals = require('./globals');

program
	.description('Add todo item')
	.option('-m, --msg <text-required>', 'Todo item (message)') 
	.option('-p, --priority <number-required>', 'todo item\'s priority (1-5, default:3)', 3) 
	.option('-s, --secret', 'Secret mode', false)
	.parse(process.argv);

/**
 *	Options
 */
const todo = program.msg;
const secret = program.secret; 
const priority = program.priority;
// const secret = program.secret ? program.secret : false;


/**
 *	Validation	
 */
//if (!todo && !secret) {
if (!todo) {
	console.error(chalk.red.bold('Options required'));
	program.help();
	process.exit(1);
}


/**
 *	Verbose	
 */
console.log(chalk.green.bold('add command ; '), "+", chalk.white.underline(todo));
if (secret)
	console.log(chalk.red.bold('- Secret mode -'));
else
	console.log(chalk.cyan.bold('- Public mode -'));
	

/**
 *	Read JSON file	
 */
const TODO_FILE = globals.TODO_FILE; 
let todos = []

fs.readFile(TODO_FILE, 'utf-8', (err, data) => {
	if (!err) {
		todos = JSON.parse(data);
	}

	const item = { todo, secret, priority };
	item[globals.ADD_AT] = Date.now();
	todos.push(item);
	
	fs.writeFile(TODO_FILE, JSON.stringify(todos), 'utf-8', (err) => {
		if (err) {
			console.error(chalk.red.bold(err));	
		} else {
			console.log(chalk.green.bold('Added Successfully'));	
		}
	});
});

