#!/usr/bin/env node
/**
 *	TODO: -2 디폴트값을 0으로 하면..
 */

const program  = require('commander');
const chalk = require('chalk');

const fs = require('fs');

const globals = require('./globals');

program
	.description('Change the order of two items (idx)\n  or, give it the highest priority if you set --first(-f) option only')
	.option('-f, --first <required>', 'first item') 
	.option('-s, --second <required>', 'second item', -1) 
	.parse(process.argv);

/**
 *	Options
 */
const first = program.first;
const second = program.second;

/**
 *	Validation	
 */
if (!first && !second) {
	console.error(chalk.red.bold('Options required'));
	program.help();
	process.exit(1);
}

/**
 *	Verbose	
 */
if (second == -1) { 
	console.log(
		chalk.green.bold('co command ; '), 
		chalk.green.bold('put highest priority on ' + chalk.yellow('#' + first)), 
	);	
} else if (first >= 0 && second >= 0) {
	console.log(
		chalk.green.bold('co command ; '), 
		chalk.green.underline(first) , chalk.magenta(" <---> "), chalk.green.underline(second));
}

/**
 *	Read JSON file	
 */
let todos = []
const TODO_FILE = globals.TODO_FILE; 

fs.readFile(TODO_FILE, 'utf-8', (err, data) => {
	if (err) {
		console.log(chalk.yellow.bold(globals.EMPTY_MSG));
	} else {
		todos = JSON.parse(data);
	}

	const tmp = todos[first];
	if (first >= 0 && second >= 0) {
		todos[first] = todos[second];
		todos[second] = tmp;
	} else {
		todos.splice(first, 1);
		todos.unshift(tmp);
	}
	
	fs.writeFile(TODO_FILE, JSON.stringify(todos), 'utf-8', (err) => {
		if (err) {
			console.error(chalk.red.bold(err));	
		} else {
			console.log(chalk.green.bold('Changed Successfully'));	
		}
	});
	// fin write
});

