#!/usr/bin/env node
/**
 *	TODO: -2 디폴트값을 0으로 하면..
 */

const program  = require('commander');
const chalk = require('chalk');

const fs = require('fs');

const globals = require('./globals');

program
	.description('Change the priority of an items')
	.option('-i, --idx <required>', 'todo item\'s index at which the prioirty will be updated') 
	.option('-p, --priority <required>', 'prioirty of a todo item') 
	.parse(process.argv);

/**
 *	Options
 */
const idx = program.idx;
const priority = parseInt(program.priority);

/**
 *	Validation	
 */
const gotAllOptions = idx && priority
if (!gotAllOptions) {
	console.error(chalk.red.bold('Options required'));
	program.help();
	process.exit(1);
}

/**
 *	Verbose	
 */
console.log(chalk.green.bold('cpr command ; '));	

/**
 *	Read JSON file	
 */
let todos = []
const TODO_FILE = globals.TODO_FILE; 

fs.readFile(TODO_FILE, 'utf-8', (err, data) => {
	if (err) {
		console.log(chalk.yellow.bold(globals.EMPTY_MSG));
	} else {
		todos = JSON.parse(data);
	}

	todos[idx].priority = priority;
	
	fs.writeFile(TODO_FILE, JSON.stringify(todos), 'utf-8', (err) => {
		if (err) {
			console.error(chalk.red.bold(err));	
		} else {
			console.log(chalk.green.bold('Changed Successfully'));	
		}
	});
	// fin write
});

