#!/usr/bin/env node
/**
 *	TODO: -2 디폴트값을 0으로 하면..
 */

const program  = require('commander');
const chalk = require('chalk');

const fs = require('fs');

const globals = require('./globals');

program
	.description('Change two item\'s order(idx)')
	.option('-1, --first <required>', 'first item') 
	.option('-2, --second <required>', 'second item', 0) 
	.parse(process.argv);

/**
 *	Options
 */
const first = program.first;
const second = program.second;


/**
 *	Validation	
 */
if (!first && !second) {
	console.error(chalk.red.bold('Options required'));
	program.help();
	process.exit(1);
}

/**
 *	Verbose	
 */
console.log(chalk.green.bold('co command ; '), chalk.green.underline(first) , chalk.magenta(" <---> "), chalk.green.underline(second));
	

/**
 *	Read JSON file	
 */
let todos = []
const TODOFILE = globals.TODOFILE; 

fs.readFile(TODOFILE, 'utf-8', (err, data) => {
	if (err) {
		console.log(chalk.yellow.bold(globals.EMPTY_MSG));
	} else {
		todos = JSON.parse(data);
	}

	const tmp = todos[first];
	todos[first] = todos[second];
	todos[second] = tmp;
	
	fs.writeFile(TODOFILE, JSON.stringify(todos), 'utf-8', (err) => {
		if (err) {
			console.error(chalk.red.bold(err));	
		} else {
			console.log(chalk.green.bold('Changed Successfully'));	
		}
	});
	// fin write
});

