#!/usr/bin/env node

/**
 *	TODO: fin 할 때 코멘트를 추가할 수 있는 기능
 *	TODO: fin 할 때 완료 시간 추가 + add 시 생성 시간 및 목표 시간 입력받기?
 */

const program  = require('commander');
const chalk = require('chalk');
const inquirer = require('inquirer');

const fs = require('fs');

const settings = require('./settings');
const utils = require('./utils');

program
	.description('Finish todo item')
	.option('-i, --idx <index-required>', 'Index of item want to finish') 
	.parse(process.argv);

/**
 *	Options
 */
const idx = program.idx;

/**
 *	Validation	
 */
if (!idx) {
	console.error(chalk.red.bold('Option required'));
	program.help();
	process.exit(1);
}

/**
 *	Verbose	
 */
console.log(chalk.green.bold('fin command ; '), "idx :", chalk.yellow.underline(idx));

/**
 *	Read JSON file	
 */
const TODOFILE = settings.TODOFILE;
const FINFILE = settings.FINFILE;
let todos = []

fs.readFile(TODOFILE, 'utf-8', (err, data) => {
	if (err) {
		console.error(chalk.red.bold(err));
		return;
	} else {
		todos = JSON.parse(data);
	}

	const questions = [
		{
			message: "Want to finish " + idx + "th item '" + chalk.bgGreen(todos[idx].todo) + "'?",
			type: "confirm",
			name: "confirm"
		}
	];
	inquirer.prompt(questions).then((answers) => {
		if (!answers.confirm) {
			console.log(chalk.yellow.bold("Nothing happened :)"));	
			return;
		}
		
		const finItem = todos[idx];
		todos.splice(idx, 1);
		utils.writefile(TODOFILE, JSON.stringify(todos), undefined);
		
		// 완료 목룍 반영
		let fins = [];
		if (fs.existsSync(FINFILE)) {
			fins = JSON.parse(fs.readFileSync(FINFILE, 'utf8'));
		}
		fins.push(finItem);
		utils.writefile(FINFILE, JSON.stringify(fins), "Finished Successfully");
	});

	// fin write
});

