#!/usr/bin/env node

/**
 *	TODO: 다양한 방식의 보여주기 (통계나, 완료시간 기준)
 */

const program  = require('commander');
const chalk = require('chalk');

const globals = require('./globals');

const fs = require('fs');

const request = require('request');

program
	.description('Show finished items')
	.option('-a, --all', 'Show all items (default: false)', false)
	.option('-n, --number [optional]', 'Show n-items only', 10) 
	.parse(process.argv);

/**
 *	Options
 */
const all = program.all;
const number = program.number;

/**
 *	Validation
 */
if (false) { /* vali */ }

/**
 *	Verbose	
 */
console.log(chalk.green.bold('lsf command'));
	
/**
 *	Read JSON file	
 */
const FINFILE = globals.FINFILE;

if (fs.existsSync(FINFILE)) {
	fins = JSON.parse(fs.readFileSync(FINFILE, 'utf8'));
} else {
	console.log(chlak.red.underline("No finished items"));		
}

for (i = 0; i < fins.length; i++){
	if (!all && (number > 0 && number <= i)) break;
	console.log(chalk.cyan(i) + ". " + chalk.yellow.bold(fins[i].todo));	
}

