#!/usr/bin/env node

/**
 * TODO: 없는 채널 입니다
 */

const program  = require('commander');
const chalk = require('chalk');

const fs = require('fs');

program
	.option('-i, --id <required>', 'Channel id') 
	.parse(process.argv);

/**
 *	Options
 */
const id = program.id.trim();


/**
 *	Validation	
 */
if (!id) {
	console.error(chalk.red.bold('Options required'));
	program.help();
	process.exit(1);
}

/**
 *	Verbose	
 */
console.log(chalk.green.bold('subch command ; '));

/**
 *	Read JSON file	
 */
const SUBCHFILE = "subch.json";
/**
 *	subch.json ; subscribed channels meta data 
 *	{ "id" : channel-id, "synced": [synced todo item's timestamp] }
 */

let channels = []
fs.readFile(SUBCHFILE, 'utf-8', (err, data) => {
	if (err) {
		console.error(chalk.red.bold(err));
		console.log(chalk.yellow.bold("--> New file will be created"));
	} else {
		channels = JSON.parse(data);
	}

	// add item
	const item = {'id': id, 'synced': []};
	channels.push(item);
	
	/**
	 *	Write JSON file
	 */
	fs.writeFile(SUBCHFILE, JSON.stringify(channels), 'utf-8', (err) => {
		if (err) {
			console.error(chalk.red.bold(err));	
		} else {
			console.log(chalk.green.bold('Added Successfully'));	
		}
	});
	// fin write
});

